import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFD6BF',
  },
  subcontainer: {
    backgroundColor: '#F9FAFB',
    width: 390,
    height: 600,
    marginTop: 30,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  piccontainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  btn: {
    marginTop: 44,
    width: 150,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 1.5,
    borderRadius: 16,
  },
  register_btn: {
    width: 100,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'white',
    borderWidth: 1.5,
    borderRadius: 16,
  },
  imgopt: {
    marginTop: 10,
    width: 150,
    height: 120,
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
    borderWidth: 1.5,
    borderRadius: 16,
    shadowColor: 'rgba(107, 118, 132, 0.1)',
  },
  textbox: {
    width: 250,
    height: 30,
    backgroundColor: '#FFD6BF',
    borderColor: '#000000',
    borderWidth: 1,
    fontSize: 15,
    textAlign: 'center',
    borderRadius: 10,
  },
  inputText: {
    margin: 20,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    marginVertical: '1%',
    backgroundColor: '#FFFFFF',
    shadowColor: 'rgba(107, 118, 132, 0.1)',
    width: 342,
    height: 53,
    borderRadius: 16,
  },
  text: {
    color: '#6B7684',
  },
});
