import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFD6BF',
  },
  subcontainer: {
    width: 375,
    height: 584,
    marginTop: 83,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
  },
  logo: {
    marginTop: '5%',
    width: '50%',
    height: '15%',
  },
  buttonContainer: {
    marginTop: '2%',
    flexDirection: 'row',
    paddingHorizontal: '10%',
    paddingVertical: '5%',
    // backgroundColor: 'white',
  },
  button: {
    alignItems: 'center',
    paddingHorizontal: '8%',
    paddingVertical: '4%',
    marginHorizontal: '3%',
    backgroundColor: '#FFF7F4',
    borderColor: '#FFFFFF',
    borderWidth: 1.5,
    borderRadius: 15,
  },

  btnText: {
    color: 'black',
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center', //요거추가함(by loginHomestyle)
  },

  item: {
    paddingHorizontal: '30%',
    paddingVertical: '10%',
    marginVertical: 8,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
  },
  title: {
    fontSize: 18,
    color: 'black',
  },
  completed: {
    backgroundColor: '#ccc',
  },

  // 아래는 ingredient style들임.
  piccontainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  btn: {
    marginTop: 44,
    width: 150,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 1.5,
    borderRadius: 16,
  },
  btn_2: {
    width: 342,
    height: 53,
    backgroundColor: 'red', //#FFF7F4
    justifyContent: 'center',
    margin: 20,
    alignItems: 'center',
    borderRadius: 16,
  },
  addbox: {
    backgroundColor: 'black',
    marginTop: 10,
    paddingHorizontal: 5,
    paddingVertical: 5,
    flexDirection: 'row',
  },
  imgopt: {
    marginTop: 10,
    width: 100,
    height: 100,
  },
  addcompo: {
    width: 30,
    height: 30,
    backgroundColor: '#FFD6BF',
    borderColor: '#000000',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textbox: {
    width: 250,
    height: 30,
    backgroundColor: '#FFD6BF',
    borderColor: '#000000',
    borderWidth: 1,
    fontSize: 15,
    textAlign: 'center',
    borderRadius: 10,
  },
  column: {
    flexDirection: 'column',
  },
  inputText: {
    margin: 20,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    marginVertical: '1%',
    backgroundColor: 'yellow',
    width: 342,
    height: 53,
    borderRadius: 16,
  },
  text: {
    color: '#6B7684',
  },
  //아래는 loginStyles.tsx꺼
  inputContainer: {
    // backgroundColor: 'white',
    marginTop: '3%',
    paddingHorizontal: '10%',
    paddingVertical: '2%',
  },

  //아래는 MyPageScreenStyle
  thirdContainer: {
    width: 300,
    height: 150,
    marginTop: 40,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    borderRadius: 15,
  },
  imageContainer: {
    margin: 25,
    width: 100,
    height: 100,
    borderRadius: 100,
    backgroundColor: 'beige',
    overflow: 'hidden',
  },
  textContainer: {
    paddingHorizontal: 60,
    paddingVertical: 30,
    margin: 10,
    // backgroundColor: 'teal',
    flexDirection: 'column',
  },
  ingContainer: {
    width: 300,
    height: 300,
    marginTop: 83,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    alignItems: 'center',
  },
  //아래는 signup Style
  inputText2: {
    fontSize: 15,
    textAlign: 'center',
    fontWeight: 'bold',
    marginVertical: '1%',
    paddingHorizontal: '40%',
    paddingVertical: '3%',
    backgroundColor: '#FFF7F4',
    borderColor: '#FFFFFF',
    borderWidth: 1.5,
    borderRadius: 16,
    // flex: 0,
  },
  BirthBtn: {
    alignContent: 'center',
    // padding: '1%',
    paddingHorizontal: '20%',
    backgroundColor: '#FFF7F4',
    borderColor: '#FFFFFF',
    borderWidth: 1.5,
    borderRadius: 15,
  },
  //아래는 recruit
  textContainer2: {
    backgroundColor: 'white',
    paddingHorizontal: '30%',
    marginTop: '5%',
    paddingVertical: '2%',
    borderRadius: 5,
  },
  text2: {
    marginTop: '5%',
    textAlign: 'center',
    color: '#000000',
    fontSize: 20,
    fontWeight: 'bold',
  },
  button2: {
    //모집글 등록하기 버튼
    marginTop: '4%',
    marginHorizontal: '5%',
    justifyContent: 'space-between',
    paddingHorizontal: '20%',
    paddingVertical: '2%',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 1.5,
    borderRadius: 5,
  },
  itemContainer: {
    // flex: 1,
    // backgroundColor: 'black',
    paddingHorizontal: '30%',
    paddingVertical: '5%',
    paddingBottom: '5%',
  },
  ShowboxContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  item2: {
    paddingHorizontal: 30,
    paddingVertical: 20,
    backgroundColor: '#FFF7F4',
    alignItems: 'center',
    marginVertical: '5%',
    marginHorizontal: '5%',
    borderWidth: 1.5,
    borderColor: '#000000',
    borderRadius: 5,
  },
  joinbtncontainer: {
    justifyContent: 'center',
    borderRadius: 5,
    // padding: 5,
    borderColor: 'white',
  },
  joinbtn: {
    justifyContent: 'space-between',
    fontSize: 15,
    fontWeight: 'bold',
  },
  chatcontainer: {
    marginTop: 24,
    marginLeft: 24,
  },
});
